# frozen_string_literal: true

source 'https://rubygems.org'

group :system do
	gem 'bundler'
	gem 'gorilla_patch'
	# gem 'httpx'
	gem 'memery'
	gem 'pry-byebug'
	# gem 'rubyzip'
end

group :server do
	gem 'flame', github: 'AlexWayfer/flame'
	gem 'flame-flash', github: 'AlexWayfer/flame-flash'
	gem 'puma'
	gem 'rack-contrib'
	## https://github.com/mwpastore/rack-protection-maximum_cookie/pull/4
	gem 'rack-protection-maximum_cookie',
		github: 'AlexWayfer/rack-protection-maximum_cookie',
		branch: 'update_rack_dependency'
	gem 'rack-slashenforce'
	gem 'rack-utf8_sanitizer'
	gem 'rack_csrf', require: 'rack/csrf'
end

group :development do
	gem 'filewatcher'
end

group :linter do
	gem 'bundler-audit'
	gem 'rubocop'
	gem 'rubocop-performance'
	gem 'rubocop-rspec'
end

# group :database do
# 	gem 'pg'
# 	gem 'sequel'
# 	gem 'sequel-enum_values', require: 'sequel/plugins/enum_values'
# 	gem 'sequel_pg', require: 'sequel'
# 	gem 'sequel_secure_password'
# end

# group :translations do
# 	gem 'flame-r18n', github: 'AlexWayfer/flame-r18n'
# 	gem 'r18n-core', github: 'r18n/r18n'
# end

# group :forms do
# 	gem 'formalism', github: 'AlexWayfer/formalism'
# end

group :views do
	gem 'erubi', require: 'tilt/erubi'
end

# group :mails do
# 	gem 'email_address'
# 	gem 'mail'
# end

# group :test do
# 	gem 'database_cleaner'
# 	gem 'fabrication'
# 	# gem 'page-object'
# 	gem 'rack-test'
# 	gem 'rspec'
# end

group :others do
	# gem 'faker'
	# gem 'kramdown'
	# gem 'retries',
	# gem 'money-oxr',
	# 	## https://github.com/edlebert/money-oxr/pull/7
	# 	github: 'AlexWayfer/money-oxr', branch: 'add_flock_for_cache'
	# 	## https://github.com/ooyala/retries/pull/9
	# 	github: 'AlexWayfer/retries', branch: 'v2'
	# gem 'sentry-raven'
	# gem 'shrine'
	# gem 'tzinfo'
	# gem 'tzinfo-data'
	## https://github.com/biola/Voight-Kampff/pull/38
	# gem 'voight_kampff', github: 'AlexWayfer/Voight-Kampff', branch: 'v2'
end

group :toys do
	gem 'benchmark_toys_template', path: '~/Projects/ruby/benchmark_toys_template'
	gem 'diffy'
	gem 'paint'
	gem 'pry'
	gem 'pry-doc'
	gem 'rack-console'
	gem 'toys'
end

# group :benchmark do
# 	gem 'benchmark-ips'
# 	gem 'benchmark-memory'
# end
