Layout/Tab:
  Enabled: false
  IndentationWidth: 2
Layout/IndentationWidth:
  Width: 1
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Style/ParenthesesAroundCondition:
  AllowInMultilineConditions: true

AllCops:
  TargetRubyVersion: 2.5

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - '*.gemspec'
